### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by jiyuanj** [bunnech/cellot#11]
In training data phase. Ran python ./scripts/train.py --outdir ./results/4i/drug-cisplatin/model-cellot --config ./configs/tasks/4i.yaml --config ./configs/models/cellot.yaml --config.data.target cisplatin and it terminated with AssertionError.
<img width="565" alt="Screenshot 2024-01-19 at 3 36 58 PM" src="https://github.com/bunnech/cellot/assets/130794775/bd8dda16-5231-4ee9-9789-13d14cc95311">

**Comment by stefangstark** [comment]
Please ensure that you have [downloaded the data](https://polybox.ethz.ch/index.php/s/RAykIMfDl0qCJaM) and it is in the correct location. All paths are relative to the git repo. So for instance, this error is thrown because it cannot find `./datasets/4i/features.txt`
