### ISSUE TITLE
OOD train test split question

### ISSUE THREAD

**Issue by DanLesman** [bunnech/cellot#12]
Hi! 

I am using CellOT in the OOD setting and I was wondering why you were using a test_size > 0 for split_cell_data_train_test in the ood setting? My thinking is that in OOD you would want to use all the data you can that's outside of the holdout group. Is it for evaluating the performance of the non-ood tasks or maybe something else I am missing? 

Thank you so much!

**Comment by stefangstark** [comment]
Hi Dan,

We wanted the test set to be the same for all experiments, iid and ood

Best,
Stefan
