### ISSUE TITLE
Missing plots data in the results folder

### ISSUE THREAD

**Issue by jiyuanj** [bunnech/cellot#16]
After trained cellot, cae-4i, random, identity and scgen-4i models for 4i data, I tried running plot.py script by this command: python scripts/plot.py, I encountered error on file not found when plotting UMAP and KNN_MMD
<img width="563" alt="Screenshot 2024-03-15 at 1 28 28 AM" src="https://github.com/bunnech/cellot/assets/130794775/bb1ba2c2-1180-450f-9c0c-062afcf0db53">
This indicates umap.csv and knn_enrichment.csv are missing in evals_iid_data_space of results folder. Could you please tell me is there anything wrong? Is my command correct for running this plot script?
Thanks.

**Comment by bunnech** [comment]
No, it cannot find the UMAP evaluation results from CellOT. You will need to run `scripts/evaluate.py` before `scripts/plot.py`. Might be that UMAP is not anymore included in `scripts/evaluate.py` as it is a method that in generally should not be used for quantitative evaluation. In that case, just remove those lines from `scripts/plot.py`.
