### ISSUE TITLE
The R2 metric

### ISSUE THREAD

**Issue by ghost** [bunnech/cellot#19]
Hi !
In ./scripts/evaluate.py, The r2 between the observed and predicted gene expression is calculated using "pd.Series.corr(mut, mui)". However, this function only returns the Pearson correlation coefficient (PCC). I is there anything wrong ?

**Comment by stefangstark** [comment]
Hi, thanks for spotting this! I took a closer look myself and we actually do report the correlation coefficient but are calling it r^2 by mistake. Also if you look in the text we even define r^2 as the correlation coefficient, and some models are reporting a negative value for r^2. So basically all the r^2 in the paper should really be r.

In terms of model comparisons, this won't change any statements we make. Hopefully you don't feel mislead about the difference in interpretation between r and r^2. We will look into what we can do about amendments.
