### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by yanwu2014** [bunnech/cellot#2]
Hi,

Thanks so much for the great tool! I was wondering if there's a way to use GPUs using the current training framework or if you were planning on adding GPU support in the near future?

Thanks!
Yan

**Comment by mksingh2104** [comment]
GPU acceleration would be greatly appreciated.

Sincerely,

**Comment by bunnech** [comment]
Yes, it was originally planned but did not happen yet. In case you would like to add a PR, let us know!
