### ISSUE TITLE
target key in config, 4i.yaml

### ISSUE THREAD

**Issue by Ralmohsen** [bunnech/cellot#22]
Hi, I would like to ask about this:
In https://github.com/bunnech/cellot/blob/main/configs/tasks/4i.yaml

we have  source: control, but we do not have any key for target. My question is how the target/predicted samples are labeled?

Thank you

**Comment by bunnech** [comment]
`target` is any drug for which you want to run CellOT. Try `erlotinib` for example.

**Comment by TedSIWEILIU** [comment]
Where do we find the 4i data?
