### ISSUE TITLE
fail to open the file“hvg-train-only.h5ad”in scrna-crossspecies

### ISSUE THREAD

**Issue by suxiaoman666888** [bunnech/cellot#23]
when i try to use anndata to read the file“hvg-train-only.h5ad”in scrna-crossspecies,i failed.
but i successfully read the file 4i-melanoma_cell_lines-8h.h5ad in cl-8h
The error message is as follows
AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.

I don't know why, looking forward to your reply，thanks.

**Comment by bunnech** [comment]
This might be due to the version of `scanpy` and `anndata`. Please check to use the latest version.
