### ISSUE TITLE
How can we train a model with multiple targets in the ood mode? 

### ISSUE THREAD

**Issue by weizhiting** [bunnech/cellot#25]
Hi, thanks for this great job.
I can run the sciplex3 dataset with one target in the ood mode? But this will time-consuming as the sciplex3 have 188 drugs in total.  So Whether can we train the model with multiple targets once? 

Best
Hope to receive your reply.

**Comment by bunnech** [comment]
To run `sciplex3` on a particular target drug, you need to specify the `target` in the `config` file. So either add `target: drugname ` below `data` in this config file (https://github.com/bunnech/cellot/blob/main/configs/tasks/sciplex3-ood.yaml) or add a flag `--target drugname` to the Python command. Make sure that `drugname` is fully lowercase.

Hope this helps!

**Comment by weizhiting** [comment]
I'm sorry I didn't explain my question clearly.  But what I want to ask is,  For example, if i want to predict the outcome of 3 drugs, respectively, how to set the `target` parameter?  (1) `target: drug A, drug B, drug C?` (2) or for every drug i want to predict, should train a model?
