### ISSUE TITLE
How to set the parameter target if i want to predict the outcome of multiple drugs? 

### ISSUE THREAD

**Issue by weizhiting** [bunnech/cellot#26]
Hi,
In the sciplex dataset ood mode, if i want to predict the outcome of multiple drugs, how to set the parameter `target` in the config file?  (1) `target: drug A,   drug B  ,... , drug N`.  For example, if i want to predict the outcome of 3 drugs, respectively, `target: drug A, drug B, drug C`?  (2) or `for every drug` i want to predict, i should `train a new model`? 

Best, 
Hope to receive your reply.

**Comment by stefangstark** [comment]
Yes, every drug is its own model. You can either specify N configs or see [here](https://github.com/bunnech/cellot/blob/ff287783325c051811fed51fc6dfcb69db56c8c5/scripts/submit/iid.sh#L30) for an example of how to set config params from the command line.
