### ISSUE TITLE
Generating predictions using CellOT

### ISSUE THREAD

**Issue by yanwu2014** [bunnech/cellot#3]
Hi!

I wasn't able to find a way to generate predicted expression values using a trained CellOT model, do you have a script to do so?

Thanks,
Yan

**Comment by bunnech** [comment]
In general, you can follow the code in the evaluation script (https://github.com/bunnech/cellot/blob/main/scripts/evaluate.py). Make sure that you are loading the right model, i.e., in case you use an autoencoder embedding, load both the trained autoencoder and the trained CellOT model. Also make sure that your configs are set correctly, i.e., the config file contains the correct path to the trained autoencoder. Then encoding the data is handled within the [load_data](https://github.com/bunnech/cellot/blob/main/cellot/utils/evaluate.py#L169) function, i.e., specifically [in this line](https://github.com/bunnech/cellot/blob/main/cellot/data/cell.py#L149). So your test data of interest need to be passed here. Once you loaded all your inputs including models and data, you transport your cells of interest into the perturbed state as done [here](https://github.com/bunnech/cellot/blob/main/cellot/utils/evaluate.py#L333), and lastly decode your predictions as done in [this line](https://github.com/bunnech/cellot/blob/main/cellot/utils/evaluate.py#L337).

Hope this helps!
