### ISSUE TITLE
How to speed up the training process?

### ISSUE THREAD

**Issue by weizhiting** [bunnech/cellot#33]
Hi, thanks for this great job.

For datasets with large perturbations and cell lines in the `ood` mode, if I want to test the prediction performance of each perturbation on each cell line using CellOt, training the CellOt model will be very time-consuming (20 * 10 models, #26 as @stefangstark says, every perturbation is its own model). Is there any way to accelerate the training process？ 

Thanks advance for your reply.

**Comment by stefangstark** [comment]
hi, a couple suggestions below -- I hope they are useful!

1) you can "pool" cell lines across perturbations. So if you have 20 perturbations and 10 cell lines you can concatenate the 10 cell line datasets into one and then train 20 models. 

2) you can look into early stopping criteria to speed up the training of the individual models. IIRC we did not need them in this work as the compute requirements were well within our budgets

3) the usual acceleration tricks may help here too. these tend to be specific to your compute environment. for the purposes of this publication, we were able to just use individual cpus.

**Comment by weizhiting** [comment]
Thanks for your reply.
As for the suggestion (1) In the `iid` mode, i can concatenate the 10 cell line datasets into one and then train 20 models. But in the `ood` mode, every time i should held out a specific cell line and then train a model for each perturbation, resulting in the 20 * 10 models. Am i understand correctly?

I will  try the suggestion 2 and 3.  Thanks again for your advices.
