### ISSUE TITLE
Generalization to unseen cell types

### ISSUE THREAD

**Issue by ArturDev42** [bunnech/cellot#34]
Hi @bunnech @stefangstark, I am trying to understand if CellOT is designed to generalize to unseen cell types? I didn't see that explicitly mentioned in the paper. However, I noticed that in [sciplex3-ood.yaml](https://github.com/bunnech/cellot/blob/ff287783325c051811fed51fc6dfcb69db56c8c5/configs/tasks/sciplex3-ood.yaml) one cell type is excluded from model training. Does it make sense to test CellOT on a cell type that it has not seen during training? If yes, how is CellOT learning cell type specific information? Thank you!

**Comment by stefangstark** [comment]
generalizing to unseen cell types is a type of OOD experiment. So yes you can use CellOT in this setting, but your milage may vary. Some factors that influence success will include the number of cell lines, their specific similarities/differences, the types of perturbations you are interested in, etc.

We have some discussion around extended data figure 6 in the paper that addresses when OOD settings succeed/fail.

**Comment by ArturDev42** [comment]
Thanks for the response @stefangstark. I'm running an OOD experiment using sciplex3 data. I expect the results on an unseen cell type to be worse than if the model has seen all cell types during training. Why would CellOT be capable of generalizing to unseen cell types if it is not conditioned on cell types?

From the paper and the discussion here https://github.com/bunnech/cellot/issues/29#issuecomment-2175656631 I understand that how you define the OOD setting is that after the model has learned the response of seen control cells to a specific treatment, it can generalize to unseen control cells. I assume the premise is that the unseen control cells have the same cell type as the cells seen during training.
