### ISSUE TITLE
Data link broken

### ISSUE THREAD

**Issue by jannisborn** [bunnech/cellot#36]
A colleague just told me that your data link is down: https://polybox.ethz.ch/index.php/s/RAykIMfDl0qCJaM

**Comment by kiristern** [comment]
Hello, is there an updated link for the datasets? I'm also running into a broken link issue. Thanks!

**Comment by kiristern** [comment]
I just used the link from the Nature paper: https://www.research-collection.ethz.ch/handle/20.500.11850/609681
