### ISSUE TITLE
Any example for o.o.s?

### ISSUE THREAD

**Issue by huboqiang** [bunnech/cellot#5]
Hi, as mentioned in README.md

>All scripts to reproduce the experiments in the i.i.d. (independent-and-identically-distributed), o.o.s. (out-of-sample), and o.o.d. (out-of-distribution) setting can be found in scripts/submit

I tried to find `./configs/tasks/oos-lupuspatients.yaml` in `scripts/submit/oos-lupuspatients.sh`, but only found `lupuspatients.yaml` and `lupuspatients-ood.yaml`. 

So is there any example for o.o.s? 

Thanks.

**Comment by stefangstark** [comment]
Hi, You can use those configs. So actually the model treats the oos and ood tasks the same way. We made the distinction because of how the lupus patients data was collected, i.e. processed it was as a single batch.
