### ISSUE TITLE
No such file or directory：'datasets/scrna-sciplex3/hvg-top1k-train-only.h5ad'

### ISSUE THREAD

**Issue by ZexiChen502** [bunnech/cellot#9]
Hello, 
when I try to train  Sciplex3,  it requires the  hvg-top1k-train-only.h5ad. But only hvg.h5ad exists in the download dataset. Is that  any scripts to preprocess the hvg.h5ad? Or I could just rename the file?

thanks

**Comment by bunnech** [comment]
Thanks for reaching out. We still had a link to the old datasets. I updated the README and it now points to the folder with all preprocessed datasets. Apologies for this oversight! Please check that the `.zip` file is 1.9 GB instead of 398.9 MB (that's the old file)?

**Comment by ZexiChen502** [comment]
Now it works！❤❤❤

**Comment by poseidonchan** [comment]
Hi, Could you please provide the corresponding data link again? I think the link is not working now.

**Comment by duncster94** [comment]
Hi, the link in the README still points to the old file.
